config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :posts
  end
  resources :helps
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  Rails.application.routes.draw do
    namespace :admin do
      resources :posts
    end

    resources :category
  end

  root to: "category#index"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/admin/account.rb
class Admin::Account < ApplicationRecord
end

app/models/admin/post.rb
class Admin::Post < ApplicationRecord
  belongs_to :category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :image

  validates_presence_of :title, on: :create, message: "can't be blank"
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_admin_post, only: %i[ show edit update destroy ]

  # GET /admin/posts or /admin/posts.json
  def index
    @admin_posts = Admin::Post.all
  end

  # GET /admin/posts/1 or /admin/posts/1.json
  def show
  end

  # GET /admin/posts/new
  def new
    @admin_post = Admin::Post.new
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts or /admin/posts.json
  def create
    @admin_post = Admin::Post.new(admin_post_params)

    respond_to do |format|
      if @admin_post.save
        format.html { redirect_to @admin_post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @admin_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/posts/1 or /admin/posts/1.json
  def update
    respond_to do |format|
      if @admin_post.update(admin_post_params)
        format.html { redirect_to @admin_post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/posts/1 or /admin/posts/1.json
  def destroy
    @admin_post.destroy!

    respond_to do |format|
      format.html { redirect_to admin_posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_post
      @admin_post = Admin::Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_post_params
      params.require(:admin_post).permit(:title, :description, :content, :category_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
    def index
      @categories = Category.all
    end

    def show
      @category = Category.find(params[:id])
      fresh_when etag: @category
    end

    def new
        @category = Category.new
    end

    def create
      @category = Category.create!(category_params)
      redirect_to category
    end

    def update
      @category = Category.find(params[:id])
    end

    def edit
      @category = Category.find(params[:id])
    end

    def destroy
      @category = Category.find(params[:id])
    end

    private
      def category_params
        params.require(:category).permit(:title, :description, :image)
      end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/admin/posts/_form.html.erb
<%= form_with(model: admin_post) do |form| %>
  <% if admin_post.errors.any? %>
    <div style="color: red">
      <h5><%= pluralize(admin_post.errors.count, "error") %> prohibited this admin_post from being saved:</h5>

      <ul>
        <% admin_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div style="margin-top: 8px">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/posts/_post.html.erb
<div id="<%= dom_id post %>" style="box-shadow: 1px 2px 4px rgba(0, 0, 0, 0.4); padding: 4px; border-radius: .5rem">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= post.category_id %>
  </p>

</div>

app/views/admin/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", admin_post: @admin_post %>

<br>

<div>
  <%= link_to "Show this post", @admin_post %> |
  <%= link_to "Back to posts", admin_posts_path %>
</div>

app/views/admin/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="admin_posts">
  <% @admin_posts.each do |admin_post| %>
    <%= render admin_post %>
    <p>
      <%= link_to "Show this post", admin_post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_admin_post_path %>

app/views/admin/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", admin_post: @admin_post %>

<br>

<div>
  <%= link_to "Back to posts", admin_posts_path %>
</div>

app/views/admin/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_post %>

<div>
  <%= link_to "Edit this post", edit_admin_post_path(@admin_post) %> |
  <%= link_to "Back to posts", admin_posts_path %>

  <%= button_to "Destroy this post", @admin_post, method: :delete %>
</div>

app/views/category/index.html.erb
<% if !@categories.blank? %>
  <% for item in @categories  %>
    <li><%= item.name %></li>
  <% end %>
  <a href="/category/new">Creer category</a>
  <a href="/admin/posts">Posts</a>
<% else %>
<p> Rien à afficher </p>
<% end %>

app/views/category/new.html.erb
<%= form_with model: @categories do |f| %>
    <div>
        <%= f.label :title, "Titre de la catégory" %>
        <%= f.text_field :title %>
    </div>

        <div>
        <%= f.label :description, "Description de la catégory" %>
        <%= f.text_area :description %>
        </div>

        <div>
        <%= f.label :title, "Image" %>
        <%= f.file_field :image %>
        </div>

<div style="margin-top: 3px">
        <%= f.submit %>
        </div>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>